version: '3.4'

services:
  
  sparepartssearch.api:
    image: ${DOCKER_REGISTRY-}sparepartssearchapi
    build:
      context: .
      dockerfile: src\Services\SparePartsSerach\SparePartsSearch.API\Dockerfile
    depends_on:
    - rabbitmq
    volumes:
    - ./volumes/Logs:C:\src\Logger
  
  rabbitmq:
    image: micdenny/rabbitmq-windows
    hostname: rabbitmq

  spareparts.api:
    image: ${DOCKER_REGISTRY-}sparepartsapi
    environment:
    - SparepartsSearchURL=http://sparepartssearch.api 
    volumes:
    - ./volumes/Logs:C:\src\Logger
    build:
      context: .
      dockerfile: src\Services\SpareParts\Web\SpareParts.Api\Dockerfile
    depends_on:
    - rabbitmq
    - spareparts.api.mongo1
  
  spareparts.api.mongo1:
    image: mongo
    volumes:
      - ./volumes/mongodb/mongo/spareparts-api/db:C:/data/db
      - ./volumes/mongodb/mongo/spareparts-api/configdb:C:/etc/mongod.conf
 