version: '3.4'

services:
  cars.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"

  sparepartssearch.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "81:80"

