version: '3.4'

services:
  cars.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"

  sparepartssearch.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "81:80"


  spareparts.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development     
    ports:
      - "82:80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
