version: '3.4'

services:
  cars.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"

  sparepartssearch.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "81:80"

  spareparts.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development     
      - SPARE_PARTS_EVENT_BUS_CONNECTION=localhost:5672
      - SPARE_PARTS_EVENT_BUS_USERNAME=guest
      - SPARE_PARTS_EVENT_BUS_PASSWORD=guest
    ports:
      - "82:80"
      


  rabbitmq:
    ports:
    - "15672:15672"
    - "5672:5672"
  
