version: '3.4'

services:
  cars.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"

  sparepartssearch.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "81:80"

  spareparts.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development     
      - SPARE_PARTS_EVENT_BUS_CONNECTION=localhost:5672
      - SPARE_PARTS_EVENT_BUS_USERNAME=guest
      - SPARE_PARTS_EVENT_BUS_PASSWORD=guest
    ports:
      - "82:80"
      
  
  spareparts.api.mongo1:
    hostname: spareparts.api.mongo1
    container_name: spareparts.api.localmongo1
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    command: [ "mongod", "--replSet", "rs0", "--dbpath", "/data/db","--bind_ip_all",]

  rabbitmq:
    ports:
    - "15672:15672"
    - "5672:5672"
